spring.application.name=api-gateway

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Employee Service
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/Employees/**

# Department Service
spring.cloud.gateway.routes[1].id=department-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/Department/**